apiVersion: v1
kind: Service
metadata:
  name: my-crazy-nginx
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    nodePort: 31484
    targetPort: 80 # port on pods
  selector:
    app: my-crazy-nginx
  type: NodePort
