apiVersion: v1
kind: Service
metadata:
  name: my-nginx
spec:
  ports:
  - name: port-1
    port: 80
    protocol: TCP
    nodePort: 31484
    targetPort: 80 # port on pods
  selector:
    app: my-nginx
  type: LoadBalancer
status:
  loadBalancer: {}

# info:
# LoadBalancer normaly is used in cloud services
# it creates also NodePort
# external IP on this test cluster is pending bec there is no LoadBalancer
# you could simulate it if you add another VM-box with the load balancer and additional
  # software which listens to the kubernetes cluster api if a service wants a LoadBalancer
